# Generated by Django 3.2 on 2023-04-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_added_models_review_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='category',
        ),
        migrations.RemoveField(
            model_name='title',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
