# Generated by Django 3.2 on 2023-04-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_Last_migrations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
    ]
